# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Setup
title:            Sergio P. Perez
tagline:          'A Jekyll theme'
description:      'President's PhD researcher at <a href="https://www.imperial.ac.uk/people/sergio.perez15" target="_blank">Imperial College London</a>.'
url:              http://sergiopperez.github.io
baseurl:          /

author:
  name:           'Sergio P. Perez'
  url:            https://twitter.com/sergiopprz

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
