# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Setup
title:            Sergio P. Perez
tagline:          'A Jekyll theme'
description:      'hello'
url:              http://sergiopperez.github.io
baseurl:          /

author:
  name:           'Sergio P. Perez'
  url:            https://twitter.com/sergiopprz

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
